# Generated by Django 3.2.4 on 2021-06-08 12:59

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=api.models.generate_unique_id, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('author', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=64)),
                ('pageCount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('readPage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('finished', models.BooleanField(default=False)),
                ('reading', models.BooleanField(default=False)),
                ('insertedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
